---
- name: first playbook
  hosts: all
  become: yes
  vars:
    - a: 10
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
      when:
        a == 10    
    - name: start web server
      service:
        name: httpd
        state: started
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart server
      service:
        name: httpd
        state: restarted

