---
- name: first playbook
  hosts: all
  become: yes
  tasks:
    - name: install httpd software
      yum:
        name: httpd
        state: latest
    - name: start web server
      service:
        name: httpd
        state: started
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
      notify: Restart web server
    - name: copy second file
      copy:
        src: index1.html
        dest: /var/www/html/index1.html
      notify: Restart web server
  handlers:
    - name: Restart web server
      service:
        name: httpd
        state: restarted
