---
- name: first playbook
  hosts: web-server
  become: yes
  vars:
    - a: httpd
    - b: latest
    - c: started
    - d: restarted

  tasks:
    - name: install httpd software
      yum:
        name: "{{a}}"
        state: "{{b}}"
    - name: start web server
      service:
        name: "{{a}}"
        state: "{{c}}"
    - name: copying the files
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: restart server
      service:
        name: "{{a}}"
        state: "{{d}}" 

